@extends('layouts.app')
@section('title','About Us | '.$site['name'])
@section('content')
<x-hero title="Professionally Managed Mobility for Business and Personal Travel" eyebrow="About us" :image="$images['corporate']">{{ $site['legal_name'] }} is a partnership firm established in 2026 for rent-a-cab, vehicle rental, chauffeur-driven mobility, corporate transportation and fleet solutions.</x-hero>
<x-section title="Brand Philosophy" :eyebrow="$site['tagline']">
    <p class="max-w-4xl text-lg leading-8 text-steel">Trinetra Fleet Solutions is positioned as a corporate mobility company, not a small local taxi operator. The website uses placeholders where verified business data is unavailable and avoids publishing sensitive partnership deed information.</p>
    <div class="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">@foreach([['Vision','To be a dependable corporate mobility partner known for disciplined coordination, clean vehicles, courteous chauffeurs and transparent communication.'],['Mission','To provide enquiry-led, professionally managed ground transport for businesses, institutions, events, families and travellers.'],['What Trinetra Means','In a business context, Trinetra represents three points of attention: customer requirement, operational readiness and service follow-through.'],['Quality Commitment','Service is planned around vehicle suitability, documentation checks, chauffeur conduct, timely coordination and clear escalation paths.'],['Safety Commitment','Safety practices are handled through driver verification, vehicle checks, women passenger safety workflows and emergency support where contracted.'],['Leadership Approach','Partner information and sensitive legal details are intentionally not published. Public leadership content can be added through verified admin settings.']] as [$title,$text])<div class="rounded border border-slate-200 bg-white p-6"><h3 class="text-xl font-semibold text-navy">{{ $title }}</h3><p class="mt-3 text-steel">{{ $text }}</p></div>@endforeach</div>
</x-section>
@endsection
